services:
    jjk.api:
        build:
            context: "./vendor/laravel/sail/runtimes/8.5"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.5/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - pgsql
            # - redis
            # - mailpit
            # - selenium
    pgsql:
        image: "postgres:13"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_ROOT_HOST: "%"
            POSTGRES_DATABASE: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_ALLOW_EMPTY_PASSWORD: 1
            POSTGRES_EXTRA_OPTIONS: "${POSTGRES_EXTRA_OPTIONS:-}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
            - "./vendor/laravel/sail/database/postgres/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sail-redis:/data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - redis-cli
    #             - ping
    #         retries: 3
    #         timeout: 5s
    # mailpit:
    #     image: 'axllent/mailpit:latest'
    #     ports:
    #         - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    #         - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - sail
    # selenium:
    #     image: selenium/standalone-chromium
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    # sail-redis:
    #     driver: local
    # sail-meilisearch:
    #     driver: local
